version: "3.7"
services:
  app:
    image: node:16.6.1-alpine
    container_name: app
    restart: unless-stopped
    working_dir: /var/www
    command: sh -c "npm install && npm start"
    ports:
      - "5000:5000"
    volumes:
      - ./:/var/www
    networks:
      - housing-authority

networks:
  housing-authority:
    driver: bridge
